# Generated by Django 6.0.4 on 2026-04-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('django_celery_outbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celeryoutbox',
            name='schema_version',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='celeryoutboxdeadletter',
            name='schema_version',
            field=models.SmallIntegerField(default=1),
        ),
    ]
